import { useRef, useState } from "react";
import useWorkspaceActions from "./workspace/useWorkspaceActions";
import useWorkspaceReads from "./workspace/useWorkspaceReads";

function useTeacherWorkspaceData() {
  const {
    profilePreferences,
    setProfilePreferences,
    classes,
    students,
    calendarDiaryEntries,
    calendarEvents,
    calendarTablesReady,
    attendanceSessions,
    attendanceEntries,
    assessments,
    setAssessments,
    assessmentEntries,
    runningRecords,
    subjects,
    units,
    rubrics,
    rubricCategories,
    rubricCriteria,
    developmentScores,
    groups,
    groupMembers,
    groupConstraints,
    loading,
    formError,
    setFormError,
    classOptions,
    loadData,
  } = useWorkspaceReads();

  const [seedingRubrics, setSeedingRubrics] = useState(false);
  const [classForm, setClassForm] = useState({
    name: "",
    gradeLevel: "",
    schoolYear: "",
    sortOrder: "",
  });
  const [studentForm, setStudentForm] = useState({
    firstName: "",
    lastName: "",
    gender: "Prefer not to say",
    classId: "",
    notes: "",
    isParticipatingWell: false,
    needsHelp: false,
    missingHomework: false,
    separationList: "",
    sortOrder: "",
  });
  const [runningRecordForm, setRunningRecordForm] = useState({
    studentId: "",
    recordDate: "",
    textTitle: "",
    totalWords: "",
    errors: "",
    selfCorrections: "",
    notes: "",
  });
  const [subjectForm, setSubjectForm] = useState({
    classId: "",
    name: "",
    description: "",
    sortOrder: "",
  });
  const [unitForm, setUnitForm] = useState({
    subjectId: "",
    name: "",
    description: "",
    sortOrder: "",
  });
  const [developmentScoreForm, setDevelopmentScoreForm] = useState({
    studentId: "",
    criterionId: "",
    rating: "3",
    date: "",
    notes: "",
  });
  const [groupGenForm, setGroupGenForm] = useState({
    classId: "",
    size: "3",
    prefix: "Group",
    clearExisting: true,
    balanceGender: false,
    balanceAbility: false,
    pairSupportPartners: false,
    respectSeparations: true,
  });
  const [constraintForm, setConstraintForm] = useState({
    studentA: "",
    studentB: "",
  });
  const [groupsShowAdvanced, setGroupsShowAdvanced] = useState(true);
  const [groupsShowSeparations, setGroupsShowSeparations] = useState(false);
  const [isGeneratingGroups, setIsGeneratingGroups] = useState(false);
  const groupsScrollTopRef = useRef(0);

  const {
    handleCreateClass,
    handleCreateStudent,
    handleUpdateStudent,
    handleDeleteClass,
    handleUpdateSortOrder,
    handleSwapSortOrder,
    handleUpdateAttendanceEntry,
    handleCreateAttendanceSessionForDate,
    handleDeleteAttendanceSession,
    handleUpdateAssessmentEntry,
    handleEnsureAssessmentEntries,
    handleUpdateAssessmentNotes,
    handleCreateRunningRecord,
    handleDeleteRunningRecord,
    handleCreateSubject,
    handleCreateUnit,
    handleDeleteUnit,
    handleCreateAssessmentForUnit,
    handleDeleteAssessment,
    handleCopyAssessmentsFromUnit,
    handleCreateDevelopmentScore,
    handleCreateDevelopmentScoreEntry,
    handleUpdateDevelopmentScore,
    handleSeedDefaultRubrics,
    handleCreateRubricTemplate,
    handleUpdateRubricTemplate,
    handleDeleteRubricTemplate,
    handleCreateRubricCategory,
    handleDeleteRubricCategory,
    handleCreateRubricCriterion,
    handleDeleteRubricCriterion,
    handleUpdateRubricCriterion,
    handleCreateCalendarDiaryEntry,
    handleUpdateCalendarDiaryEntry,
    handleDeleteCalendarDiaryEntry,
    handleCreateCalendarEvent,
    handleDeleteCalendarEvent,
    handleAddConstraint,
    handleDeleteConstraint,
    handleGenerateGroups,
  } = useWorkspaceActions({
    classes,
    students,
    attendanceSessions,
    assessmentEntries,
    assessments,
    subjects,
    units,
    rubrics,
    rubricCategories,
    rubricCriteria,
    groupConstraints,
    classForm,
    setClassForm,
    studentForm,
    setStudentForm,
    runningRecordForm,
    setRunningRecordForm,
    subjectForm,
    setSubjectForm,
    unitForm,
    setUnitForm,
    developmentScoreForm,
    setDevelopmentScoreForm,
    groupGenForm,
    constraintForm,
    setConstraintForm,
    isGeneratingGroups,
    setIsGeneratingGroups,
    setSeedingRubrics,
    setFormError,
    loadData,
  });

  return {
    profilePreferences,
    setProfilePreferences,
    classes,
    students,
    calendarDiaryEntries,
    calendarEvents,
    calendarTablesReady,
    attendanceSessions,
    attendanceEntries,
    assessments,
    setAssessments,
    assessmentEntries,
    runningRecords,
    subjects,
    units,
    rubrics,
    rubricCategories,
    rubricCriteria,
    developmentScores,
    seedingRubrics,
    groups,
    groupMembers,
    groupConstraints,
    loading,
    formError,
    setFormError,
    classForm,
    setClassForm,
    studentForm,
    setStudentForm,
    runningRecordForm,
    setRunningRecordForm,
    subjectForm,
    setSubjectForm,
    unitForm,
    setUnitForm,
    developmentScoreForm,
    setDevelopmentScoreForm,
    groupGenForm,
    setGroupGenForm,
    constraintForm,
    setConstraintForm,
    groupsShowAdvanced,
    setGroupsShowAdvanced,
    groupsShowSeparations,
    setGroupsShowSeparations,
    isGeneratingGroups,
    groupsScrollTopRef,
    classOptions,
    loadData,
    handleCreateClass,
    handleCreateStudent,
    handleUpdateStudent,
    handleDeleteClass,
    handleUpdateSortOrder,
    handleSwapSortOrder,
    handleUpdateAttendanceEntry,
    handleCreateAttendanceSessionForDate,
    handleDeleteAttendanceSession,
    handleUpdateAssessmentEntry,
    handleEnsureAssessmentEntries,
    handleUpdateAssessmentNotes,
    handleCreateRunningRecord,
    handleDeleteRunningRecord,
    handleCreateSubject,
    handleCreateUnit,
    handleDeleteUnit,
    handleCreateAssessmentForUnit,
    handleDeleteAssessment,
    handleCopyAssessmentsFromUnit,
    handleCreateDevelopmentScore,
    handleCreateDevelopmentScoreEntry,
    handleUpdateDevelopmentScore,
    handleSeedDefaultRubrics,
    handleCreateRubricTemplate,
    handleUpdateRubricTemplate,
    handleDeleteRubricTemplate,
    handleCreateRubricCategory,
    handleDeleteRubricCategory,
    handleCreateRubricCriterion,
    handleDeleteRubricCriterion,
    handleUpdateRubricCriterion,
    handleCreateCalendarDiaryEntry,
    handleUpdateCalendarDiaryEntry,
    handleDeleteCalendarDiaryEntry,
    handleCreateCalendarEvent,
    handleDeleteCalendarEvent,
    handleAddConstraint,
    handleDeleteConstraint,
    handleGenerateGroups,
  };
}

export default useTeacherWorkspaceData;
